### ISSUE TITLE
Copyright and Licences

### ISSUE THREAD

**Issue by phkrief** [Agile-IoT/agile-api-spec#16]
Folks,
I decide to go thru the copyright and license process on this repo first.
For this reason, I need to have some inputs:
   - Who is the owner of the code (name, email, organisation)
   - Did you put on purpose the Apache license file. SHould we systematically replace all these files by the Eclipse Public License ?

Thanks

**Comment by cskiraly** [comment]
fixed in https://github.com/Agile-IoT/agile-api-spec/commit/92d61aa5bc229b8fbbd18f3aa2221b7c4f0c886d
