### ISSUE TITLE
Missing methods on REST implementation compared to DBUS

### ISSUE THREAD

**Issue by curcuz** [Agile-IoT/agile-api-spec#5]
Greetings, I'm focusing on Device Discovery, pairing and data management on the **[RESTful](http://petstore.swagger.io/?url=http://agile-iot.github.io/agile-api-spec/docs/swagger/api.swagger.yml#!/default/post_protocols_protocolId_discovery)** interface.
### Discovery

I see that `/protocols/{protocolId}/discovery` can be started and stopped, so I'm expecting a different method to retrieve the discovered devices list. Is there any? Am I misunderstanding the spec?
### Data

I see that the **DBUS** spec provides, per device, the following methods:
- Read
- Write
- Subscribe
- Unsubscribe

but I can't find the equivalent on the **RESTful** spec

**Comment by hdoukas** [comment]
Ciao, 

If I understood your question about Discovery correctly, the method is [GET /devices](http://petstore.swagger.io/?url=http://agile-iot.github.io/agile-api-spec/docs/swagger/api.swagger.yml#!/default/get_devices)

About the DBUS, the methods should be the following:
GET /device/{deviceId}/lastUpdate for Read
POST /device/{deviceId}/execute/{command} to Write (i.e. send a payload to a device)
POST /device/{deviceId}/subscribe  to Subscribe to a device stream (sensor)
DELETE /device/{deviceId}/subscribe to Unsubscribe

**Comment by curcuz** [comment]
@hdoukas thanks for the explanation on the _data management_ part - can you please then clarify the meaning of `registered` device? I assumed that `GET /devices` method returns devices already paired with the gateway

**Comment by muka** [comment]
Hi @curcuz let me close this issue and let's talk on gitter in more detail https://gitter.im/Agile-IoT

**Comment by curcuz** [comment]
@muka - i see no rooms in https://gitter.im/Agile-IoT
